dms2/config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :prerequisites

  resources :document_versions

  resources :documents

  resources :project_user_roles

  resources :user_types

  resources :roles

  resources :projects

  get 'set_active' => 'projects#set_active', as: :projects_set_active
  get 'set_deactive' => 'projects#set_deactive', as: :projects_set_deactive

  get 'set_active_doc' => 'document_versions#set_active_doc', as: :set_active_doc
  get 'set_deactive_doc' => 'document_versions#set_deactive_doc', as: :set_deactive_doc

  get 'set_active_manager' => 'projects#set_active_manager', as: :projects_set_active_manager
  get 'set_deactive_manager' => 'projects#set_deactive_manager', as: :projects_set_deactive_manager

  get 'projects/:id/assign_role' => 'projects#assign_role', as: :projects_assign_role

  get 'new_document_version/:projectId/:docId' => 'document_versions#new', as: :newDocVer
  get 'view_document_version/:projectId/:docId' => 'document_versions#index', as: :docVer

  get 'upload_document' => 'projects#upload_doc'

end

dms2/app/models/prerequisite.rb
class Prerequisite < ActiveRecord::Base
  belongs_to :document
  #belongs_to :prerequisite_id
end

dms2/app/controllers/prerequisites_controller.rb
class PrerequisitesController < InheritedResources::Base

  private

    def prerequisite_params
      params.require(:prerequisite).permit(:document_id_id, :prerequisite_id_id)
    end
end

dms2/app/helpers/prerequisites_helper.rb
module PrerequisitesHelper
end

dms2/app/views/prerequisites/_form.html.erb
<%= form_for(@prerequisite) do |f| %>
  <% if @prerequisite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prerequisite.errors.count, "error") %> prohibited this prerequisite from being saved:</h2>

      <ul>
      <% @prerequisite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_id_id %><br>
    <%= f.text_field :document_id_id %>
  </div>
  <div class="field">
    <%= f.label :prerequisite_id_id %><br>
    <%= f.text_field :prerequisite_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dms2/app/views/prerequisites/edit.html.erb
<h1>Editing prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Show', @prerequisite %> |
<%= link_to 'Back', prerequisites_path %>

dms2/app/views/prerequisites/index.html.erb
<h1>Listing prerequisites</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th>Prerequisite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prerequisites.each do |prerequisite| %>
      <tr>
        <td><%= prerequisite.document_id %></td>
        <td><%= prerequisite.prerequisite_id %></td>
        <td><%= link_to 'Show', prerequisite %></td>
        <td><%= link_to 'Edit', edit_prerequisite_path(prerequisite) %></td>
        <td><%= link_to 'Destroy', prerequisite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prerequisite', new_prerequisite_path %>

dms2/app/views/prerequisites/new.html.erb
<h1>New prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Back', prerequisites_path %>

dms2/app/views/prerequisites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @prerequisite.document_id %>
</p>

<p>
  <strong>Prerequisite:</strong>
  <%= @prerequisite.prerequisite_id %>
</p>

<%= link_to 'Edit', edit_prerequisite_path(@prerequisite) %> |
<%= link_to 'Back', prerequisites_path %>