dms2/config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :prerequisites

  resources :document_versions

  resources :documents

  resources :project_user_roles

  resources :user_types

  resources :roles

  resources :projects

  get 'set_active' => 'projects#set_active', as: :projects_set_active
  get 'set_deactive' => 'projects#set_deactive', as: :projects_set_deactive

  get 'set_active_doc' => 'document_versions#set_active_doc', as: :set_active_doc
  get 'set_deactive_doc' => 'document_versions#set_deactive_doc', as: :set_deactive_doc

  get 'set_active_manager' => 'projects#set_active_manager', as: :projects_set_active_manager
  get 'set_deactive_manager' => 'projects#set_deactive_manager', as: :projects_set_deactive_manager

  get 'projects/:id/assign_role' => 'projects#assign_role', as: :projects_assign_role

  get 'new_document_version/:projectId/:docId' => 'document_versions#new', as: :newDocVer
  get 'view_document_version/:projectId/:docId' => 'document_versions#index', as: :docVer

  get 'upload_document' => 'projects#upload_doc'

end

dms2/app/models/project_user_role.rb
class ProjectUserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  belongs_to :project

  	def self.search(search)
	  if search
	  	Project.where("project_name iLIKE ?", "%#{search}%" )
	    # Project.find(:all, :conditions => ['project_name LIKE ?', "%#{search}%"])
	  else
	  	Project.all
	  end
	end
end

dms2/app/controllers/project_user_roles_controller.rb
class ProjectUserRolesController < InheritedResources::Base

  private

    def project_user_role_params
      params.require(:project_user_role).permit(:user_id_id, :role_id_id, :project_id_id)
    end
end

dms2/app/helpers/project_user_roles_helper.rb
module ProjectUserRolesHelper
end

dms2/app/views/project_user_roles/_form.html.erb
<%= form_for(@project_user_role) do |f| %>
  <% if @project_user_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_user_role.errors.count, "error") %> prohibited this project_user_role from being saved:</h2>

      <ul>
      <% @project_user_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id_id %><br>
    <%= f.text_field :user_id_id %>
  </div>
  <div class="field">
    <%= f.label :role_id_id %><br>
    <%= f.text_field :role_id_id %>
  </div>
  <div class="field">
    <%= f.label :project_id_id %><br>
    <%= f.text_field :project_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dms2/app/views/project_user_roles/edit.html.erb
<h1>Editing project_user_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_user_role %> |
<%= link_to 'Back', project_user_roles_path %>

dms2/app/views/project_user_roles/index.html.erb
<h1>Listing project_user_roles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_user_roles.each do |project_user_role| %>
      <tr>
        <td><%= project_user_role.user_id %></td>
        <td><%= project_user_role.role_id %></td>
        <td><%= project_user_role.project_id %></td>
        <td><%= link_to 'Show', project_user_role %></td>
        <td><%= link_to 'Edit', edit_project_user_role_path(project_user_role) %></td>
        <td><%= link_to 'Destroy', project_user_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project user role', new_project_user_role_path %>

dms2/app/views/project_user_roles/new.html.erb
<h1>New project_user_role</h1>

<%= render 'form' %>

<%= link_to 'Back', project_user_roles_path %>

dms2/app/views/project_user_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @project_user_role.user_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @project_user_role.role_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project_user_role.project_id %>
</p>

<%= link_to 'Edit', edit_project_user_role_path(@project_user_role) %> |
<%= link_to 'Back', project_user_roles_path %>